pipeline {
    agent any

    environment {
            SLACK_WEBHOOK = credentials('slack-webhook')
        }

    parameters {
        string(name: 'BRANCH', defaultValue: 'maris', description: 'Branch to build')
    }

    tools {
        maven 'maven'
        nodejs 'NodeJS-20'
    }

    stages {
        stage('Check Tools') {
            steps {
                sh 'docker --version || true'
                sh 'docker ps || true'
                sh 'mvn -v || true'
                sh 'node -v || true'
            }
        }

        stage('Checkout') {
            steps {
                echo "Checking out branch: ${params.BRANCH}"
                git branch: "${params.BRANCH}",
                    url: 'https://github.com/Linnie43/buy-01-git'
            }
        }

        stage('Build Backend') {
            steps {
                echo "Building backend microservices"
                dir('app/backend') {
                    sh 'mvn clean package -DskipTests -Dspring-boot.repackage.skip=true'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                echo "Building frontend application"
                dir('app/frontend') {
                sh 'npm install'
                sh 'npm run build'
             }
          }
       }

       stage('Test User Service') {
           steps {
               echo "Running user service"
               dir('app/backend/user-service') {
                   sh 'mvn test'
               }
           }
       }

       stage('Test Product Service') {
            steps {
                echo "Running product service tests"
                dir('app/backend/product-service') {
                    sh 'mvn test'
                }
            }
       }

       stage('Test Media Service') {
            steps {
                echo "Running media sevice tests"
                dir('app/backend/media-service') {
                    sh 'mvn test'
                }
            }
       }


       stage('Build Docker Images') {
            steps {
                //echo "Building Docker images"
                // sh 'docker compose -f docker-compose.dev.yml build'
                echo 'Skipping Docker image build because Dockerfiles are not present in this branch.'

              }
           }

        stage('Deploy') {
                   steps {
                       script {
                           try {
                               sh 'docker compose -f infra/docker-compose.yml down'
                               sh 'docker compose -f infra/docker-compose.yml up -d --build'
                           } catch (Exception e) {
                               echo "Deployment failed — keeping previous version"
                           }
                       }
                   }
               }

    }

    post {
        always {
            script {
            if (env.WORKSPACE) {
                cleanWs notFailBuild: true
            } else {
                echo "No workspace available; skipping cleanWs"
            }
          }
          slackSend(
              tokenCredentialId: 'slack-webhook',
              color: '#439FE0',
              message: "Job completed"
            ))
       }

        success {
             slackSend(
                  tokenCredentialId: 'slack-webhook',
                 channel: '#jenkins',
                 color: 'good',
                 message: "Job '${env.JOB_NAME}' succeeded!"
               )
        }
        failure {
             slackSend(
                  tokenCredentialId: 'slack-webhook',
                 channel: '#jenkins',
                 color: 'danger',
                 message: "Job '${env.JOB_NAME}' failed!"
               )
        }

    }


}
