FROM jenkins/jenkins:lts
USER root

# Install prerequisites
RUN apt-get update && apt-get install -y chromium \
    chromium-driver \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Install Chromium (for Angular/Karma tests) and other utilities
RUN apt-get update && \
    apt-get install -y chromium && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables for Karma/ChromeHeadless
ENV CHROMIUM_BIN=/usr/bin/chromium
ENV CHROME_BIN=/usr/bin/chromium

# Add Docker's official GPG key
RUN install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc

# Add the Docker repository to Apt sources
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install docker CLI, compose plugin, git, maven, node/npm
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      docker-ce \
      docker-ce-cli \
      containerd.io \
      docker-buildx-plugin \
      docker-compose-plugin \
      git \
      maven \
      nodejs \
      npm && \
    usermod -aG docker jenkins && \
    rm -rf /var/lib/apt/lists/*

# Ensure jenkins user owns home
USER jenkins